- name: Run the equivalent of "pacman -Syu" as a separate step
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true

- name: "Install packages"
  ansible.builtin.package:
    name:
      - htop
      - mc
      - git
      - curl
      - zsh
      - whois
      - jq
      - tlp
      - flameshot
      - filezilla
      - remmina
      - python-pip
      - python-psutil
      - cifs-utils
      - ttf-firacode-nerd
      - ansible-lint
    state: present
  become: true

- name: Install Google Chrome using yay
  kewlfft.aur.aur:
    use: yay
    name: google-chrome

- name: Install Github-Desktop using yay
  kewlfft.aur.aur:
    use: yay
    name: github-desktop-bin

- name: Install Visual Studio Code using yay
  kewlfft.aur.aur:
    use: yay
    name: visual-studio-code-bin

- name: Install VirtualBox using yay
  kewlfft.aur.aur:
    use: yay
    name: virtualbox