- name: Increase ParallelDownloads to 10
  ansible.builtin.replace:
    dest: "/etc/pacman.conf"
    regexp: '^#ParallelDownloads = 5'
    replace: 'ParallelDownloads = 10'
  become: true

- name: Run the equivalent of "pacman -Syu" as a separate step
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true

- name: "Install packages"
  ansible.builtin.package:
    name:
      - htop
      - mc
      - git
      - curl
      - zsh
      - whois
      - jq
      - flameshot
      - filezilla
      - remmina
      - python-pip
      - python-psutil
      - cifs-utils
      - ttf-firacode-nerd
      - ansible-lint
      - piper
      - lutris
      - vlc
      - ncdu
      - snapper
      - snap-pac
      - pavucontrol
      - gnome-tweaks
      - neofetch
      - plymouth
    state: present
  become: true

- name: "Install Wine dependencies for Lutris"
  ansible.builtin.package:
    name:
      - wine-staging
      - giflib
      - lib32-giflib
      - libpng
      - lib32-libpng
      - libldap
      - lib32-libldap
      - gnutls
      - lib32-gnutls
      - mpg123
      - lib32-mpg123
      - openal
      - lib32-openal
      - v4l-utils
      - lib32-v4l-utils
      - libpulse
      - lib32-libpulse
      - libgpg-error
      - lib32-libgpg-error
      - alsa-plugins
      - lib32-alsa-plugins
      - alsa-lib
      - lib32-alsa-lib
      - libjpeg-turbo
      - lib32-libjpeg-turbo
      - sqlite
      - lib32-sqlite
      - libxcomposite
      - lib32-libxcomposite
      - libxinerama
      - lib32-libgcrypt
      - libgcrypt
      - lib32-libxinerama
      - ncurses
      - lib32-ncurses
      - ocl-icd
      - lib32-ocl-icd
      - libxslt
      - lib32-libxslt
      - libva
      - lib32-libva
      - gtk3
      - lib32-gtk3
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    state: present
  become: true


- name: Install dev softwares using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - github-desktop-bin
      - visual-studio-code-bin
      - oh-my-zsh-git
      - postman-bin

- name: Install game softwares using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - lutris
      - steam
      - discord
      - protonup-qt
      - protontricks
      - wine
      - mangohud-git
      - gamemode
      # - caffeine-ng
      - libappindicator-gtk3

- name: Install chat softwares using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - discord
      - skypeforlinux-stable-bin
      - slack-desktop
      - telegram-desktop-bin
      - zoom

- name: Install utilities using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - brave-bin
      - openrgb-bin
      - corectrl
      - bottles
      - flatseal
      - kooha
      - btrfs-assistant
      - gnome-browser-connector
      - gnome-shell-extensions
      - pacman-contrib
      - gnome-shell-extension-arch-update

- name: Install fonts using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-ms-fonts
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-roboto-slab
      - ttf-ubuntu-font-family
      - ttf-windows
      - ttf-fira-code

- name: Install Gnome extensions using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-arch-update
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-vitals

- name: "Set configuration options in MangoHud file"
  lineinfile:
    path: .config/MangoHud/MangoHud.conf
    line: "{{ item.line }}"
    create: true
    state: present
  with_items:
    - { line: "## GPU Options ##" }
    - { line: "gpu_stats" }
    - { line: "gpu_temp" }
    - { line: "gpu_core_clock" }
    - { line: "gpu_mem_clock" }
    - { line: "gpu_power" }
    - { line: "gpu_text=GPU" }
    - { line: "## CPU Options" }
    - { line: "cpu_stats" }
    - { line: "cpu_temp" }
    - { line: "cpu_text=CPU" }
    - { line: "## FPS and Frametime" }
    - { line: "fps" }
    - { line: "frametime" }

- name: "Modify Kernel cmdline for CoreCtrl"
  lineinfile:
    path: /etc/kernel/cmdline
    line: "amdgpu.ppfeaturemask=0xffffffff"
    state: present
  become: true

- name: "Rebuild kernels"
  command: "reinstall-kernels"
  become: true
  ignore_errors: true

- name: "Add VM Max Map Count"
  lineinfile:
    path: /etc/sysctl.d/99-sysctl.conf
    line: "vm.max_map_count = 2147483642"
    create: true
    state: present
  become: true

- name: "Add plymouth in dracut"
  lineinfile:
    path: /etc/dracut.conf.d/plymouth.conf
    line: "add_dracutmodules+=\" plymouth \""
    create: true
    state: present
  become: true

- name: "[Gnome] Set maximize and minimize buttons"
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "'appmenu:minimize,maximize,close'"
    state: present

- name: "[Gnome] Set Nautilus view mode"
  community.general.dconf:
    key: /org/gnome/nautilus/preferences/default-folder-viewer
    value: "'list-view'"
    state: present

- name: "[Gnome] Set Nautilus sort order"
  community.general.dconf:
    key: /org/gnome/nautilus/preferences/default-sort-order
    value: "'type'"
    state: present

- name: "[Gnome] Set visible columns"
  community.general.dconf:
    key: /org/gnome/nautilus/list-view/default-visible-columns
    value: "['name', 'size', 'type', 'date_modified']"
    state: present

- name: "[Gnome] Set Nautilus zoom level"
  community.general.dconf:
    key: /org/gnome/nautilus/list-view/default-zoom-level
    value: "'small'"
    state: present

- name: "[Gnome] Set dark theme"
  community.general.dconf:
    key: /org/gnome/desktop/interface/color-scheme
    value: "'prefer-dark'"
    state: present

- name: "[Gnome] Set Clock Format"
  community.general.dconf:
    key: /org/gnome/desktop/interface/clock-format
    value: "'24h'"
    state: present

- name: "[Gnome] Touchpad settings"
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/click-method
    value: "'areas'"
    state: present

- name: "[Gnome] Tap to click"
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
    value: "true"
    state: present

- name: "[Gnome] Enable location services"
  community.general.dconf:
    key: /org/gnome/system/location/enabled
    value: "true"
    state: present

- name: "Enable and start bluetooth"
  ansible.builtin.service:
    name: bluetooth
    enabled: yes
    state: started
  become: yes