- name: "Configure DNF parallel downloads to 10"
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: max_parallel_downloads=10
  become: true

- name: Update pre-installed packages
  become: true
  become_method: sudo
  ansible.builtin.package:
    name: '*'
    state: latest

- name: "Install packages"
  ansible.builtin.package:
    name:
      - htop
      - mc
      - git
      - curl
      - zsh
      - whois
      - jq
      - tlp
      - flameshot
      - filezilla
      - remmina
      - python3-pip
      - python3-psutil
      - cifs-utils
      - ansible-lint
      - fira-code
    state: present
  become: true

- name: Importing RPM Fusion Free key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
  become: true

- name: Importing RPM Fusion Non-Free key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  become: true

- name: Enable the RPM Fusion Free repository
  ansible.builtin.package:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  become:  true
  ignore-errors: true

- name: Enable the RPM Fusion Non Free repository
  ansible.builtin.package:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  become:  true
  ignore-errors: true

#- name: "[Chrome] Add Yum signing key"
#  ansible.builtin.rpm_key:
#    key: https://dl.google.com/linux/linux_signing_key.pub
#    state: "present"
#  become: true
#- name: "[Chrome] Add repository into repo.d list"
#  ansible.builtin.yum_repository:
#    name: "google-chrome"
#    description: google-chrome repository
#    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
#    enabled: true
#    gpgcheck: true
#    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
#  become: true
#- name: "[Chrome] Install google-chrome-stable"
#  ansible.builtin.package:
#    name: "google-chrome-stable"
#    state: "present"
#    update_cache: true
#  become: true

- name: "[VirtualBox] Add Yum signing key"
  ansible.builtin.rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: "present"
  become: true
  register: vbox_result
- name: "[VirtualBox] Add repository into repo.d list"
  ansible.builtin.yum_repository:
    name: "VirtualBox"
    description: virtualbox repository
    baseurl: https://download.virtualbox.org/virtualbox/rpm/fedora/36/x86_64/
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  become: true
  when: vbox_result is succeeded
- name: "[VirtualBox] Install virtualbox"
  ansible.builtin.package:
    name: "VirtualBox-7.0"
    state: "present"
    update_cache: true
  become: true
  when: vbox_result is succeeded

- name: "[Github Desktop] Add Yum signing key"
  ansible.builtin.rpm_key:
    key: https://mirror.mwt.me/ghd/gpgkey
    state: "present"
  become: true
- name: "[Github Desktop] Add repository into repo.d list"
  ansible.builtin.yum_repository:
    name: "shiftkey"
    description: "github desktop repository"
    baseurl: https://mirror.mwt.me/ghd/rpm
    enabled: true
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://mirror.mwt.me/ghd/gpgkey
  become: true
- name: "[Github Desktop] Install github-desktop"
  ansible.builtin.package:
    name: "github-desktop"
    state: "present"
    update_cache: true
  become: true

- name: "Add Visual Studio Code repository"
  ansible.builtin.yum_repository:
    name: "vscode"
    description: Visual Studio Code Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: 1
    enabled: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_facts['os_family'] == "RedHat"
  become: true
- name: "Install Visual Studio Code"
  ansible.builtin.package:
    name: "code"
    state: "present"
  when: ansible_facts['os_family'] == "RedHat"
  become: true

- name: "Packages Cleanup"
  become: true
  become_method: sudo
  ansible.builtin.package:
    autoremove: true
