- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      update_cache: yes
      name:
      - htop
      - mc
      - git
      - curl
      - zsh
      - whois
      - uuid
      - jq
      - flameshot
      - filezilla
      state: present