- name: "Workstation customization playbook"
  hosts: localhost
  connection: local
  become: true

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/gnome.yml

  vars_files:
    - vars/main.yml