---
- name: "Workstation setup"
  hosts: "localhost"
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            theme: amuse
            plugins:
              - git
              - docker
            update_mode: auto
    # - role: exploide.dnf-automatic
    #   dnf_automatic_upgrade_type: default
    #   dnf_automatic_apply_updates: true
    #   dnf_automatic_download_updates: true
    #   become: true
    #   when: ansible_distribution == "RedHat"
    - role: petermosmans.customize-gnome
  vars:
    gnome_extensions:
      - id: 517 # Caffeine
        enable: yes
      - id: 1319 # GSConnect
        enable: yes
      - id: 4798 # Thinkpad Battery Threshold
        enable: yes
      - id: 1460 # Vitals
        enable: yes
      - id: 615 # AppIndicator and KStatusNotifierItem Support
        enable: yes
      - id: 307 # Dash to dock
        enable: yes

  tasks:
    - name: "Display the distribution"
      ansible.builtin.debug:
        msg: "Distribution : {{ ansible_facts['os_family'] }} - {{ ansible_distribution }} - {{ ansible_distribution_major_version }}"
    - name: "Display all variables/facts known for a host"
      ansible.builtin.debug:
        var: hostvars[localhost]
        verbosity: 4

    - name: OS Specific tasks
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      tags: os-tasks
      ignore_errors: true

    # - name: "Add PSUtil"
    #   ansible.builtin.pip:
    #     name: psutil
    #     state: present
    # - name: "Install Gnome Software"
    #   ansible.builtin.package:
    #     name: "gnome-software"
    #     state: "absent"
    #   when: ansible_facts['os_family'] == "RedHat"
    #   become: true

    # - name: "Install Golang"
    #   ansible.builtin.package:
    #     name: "golang"
    #     state: "present"
    #   # when: ansible_facts['os_family'] == "RedHat"
    #   become: true

    - name: "Install flatpak"
      ansible.builtin.package:
        name: "flatpak"
        state: "present"
        update_cache: true
      become: true

    - name: "Manage flathub Repository"
      community.general.flatpak_remote:
        name: "flathub"
        state: "present"
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
        method: "user"
      # become: true
    - name: "Install Zoom Flatpak"
      community.general.flatpak:
        name: "us.zoom.Zoom"
        state: "present"
        method: user
      # become: true
    - name: "Install Slack"
      community.general.flatpak:
        name: "com.slack.Slack"
        state: present
        method: user
    # - name: "Install Discord"
    #   community.general.flatpak:
    #     name: "com.discordapp.Discord"
    #     state: present
    #     method: user
    - name: "Install XIVLauncher"
      community.general.flatpak:
        name: "dev.goats.xivlauncher"
        state: present
        method: user
    # - name: "Install Lutris"
    #   community.general.flatpak:
    #     name: "net.lutris.Lutris"
    #     state: present
    #     method: user
    - name: "Install Postman"
      community.general.flatpak:
        name: "com.getpostman.Postman"
        state: present
        method: user
    - name: "Install Skype"
      community.general.flatpak:
        name: "com.skype.Client"
        state: present
        method: user
    # - name: "Install Gnome Extensions"
    #   community.general.flatpak:
    #     name: "org.gnome.Extensions"
    #     state: present
    #     method: user
    # - name: "Install Github Desktop"
    #   community.general.flatpak:
    #     name: "io.github.shiftey.Desktop"
    #     state: present
    #     method: user
    # - name: "Install ProtonUp-QT"
    #   community.general.flatpak:
    #     name: "net.davidotek.pupgui2"
    #     state: present
    #     method: user

    - name: "Unwanted KDE packages"
      become: true
      become_method: sudo
      ansible.builtin.package:
        name:
          - akgregator
          - kget
          - kmail
          - knode
          - konqueror
          - kontact
        state: absent

    - name: "Copy wallpaper files"
      ansible.builtin.copy:
        src: files/
        dest: /home/{{ ansible_user_id }}/Pictures/
        owner: root
        group: root
        mode: '0777'
      with_fileglob:
        - files/*
      become: true
      become_method: sudo
