---
- name: "Workstation setup"
  hosts: "localhost"
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            theme: amuse
            plugins:
              - git
              - docker
            update_mode: auto
#    - role: exploide.dnf-automatic
#      dnf_automatic_upgrade_type: default
#      dnf_automatic_apply_updates: true
#      dnf_automatic_download_updates: true
#      become: true
#      when: ansible_distribution == "RedHat"
  tasks:
    - name: "Display the distribution"
      ansible.builtin.debug:
        msg: "Distribution : {{ ansible_facts['os_family'] }} - {{ ansible_distribution }} - {{ ansible_distribution_major_version }}"
    - name: "Display all variables/facts known for a host"
      ansible.builtin.debug:
        var: hostvars[localhost]
        verbosity: 4

    - name: OS Specific tasks
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      tags: os-tasks
      ignore_errors: true

    # - name: "Add PSUtil"
    #   ansible.builtin.pip:
    #     name: psutil
    #     state: present
    # - name: "Install Gnome Software"
    #   ansible.builtin.package:
    #     name: "gnome-software"
    #     state: "absent"
    #   when: ansible_facts['os_family'] == "RedHat"
    #   become: true

    # - name: "Install Golang"
    #   ansible.builtin.package:
    #     name: "golang"
    #     state: "present"
    #   # when: ansible_facts['os_family'] == "RedHat"
    #   become: true

    - name: "Install flatpak"
      ansible.builtin.package:
        name: "flatpak"
        state: "present"
        update_cache: true
      become: true

    - name: "Manage flathub Repository"
      community.general.flatpak_remote:
        name: "flathub"
        state: "present"
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
        method: "user"
      # become: true
    - name: "Install Zoom Flatpak"
      community.general.flatpak:
        name: "us.zoom.Zoom"
        state: "present"
        method: user
      # become: true
    - name: "Install Slack"
      community.general.flatpak:
        name: "com.slack.Slack"
        state: present
        method: user
      # become: true
    - name: "Install Discord"
      community.general.flatpak:
        name: "com.discordapp.Discord"
        state: present
        method: user
      # become: true
    - name: "Install XIVLauncher"
      community.general.flatpak:
        name: "dev.goats.xivlauncher"
        state: present
        method: user
      # become: true
    - name: "Install Lutris"
      community.general.flatpak:
        name: "net.lutris.Lutris"
        state: present
        method: user
    - name: "Install Brave"
      community.general.flatpak:
        name: "com.brave.Browser"
        state: present
        method: user

    - name: "Unwanted KDE packages"
      become: true
      become_method: sudo
      ansible.builtin.package:
        name:
          - akgregator
          - kget
          - kmail
          - knode
          - konqueror
          - kontact
        state: absent

    - name: GNOME Preferences - Nautilus - Clock Format
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
        state: present
    - name: GNOME Preferences - Mouse - Enable touchpad Right click
      community.general.dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/click-method"
        value: "'areas'"
        state: present
    - name: GNOME Preferences - Mouse - Enable touchpad tap-to-click
      community.general.dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
        value: "true"
        state: present
    - name: "GNOME Preferences - Window Buttons"
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"
        state: "present"

    - name: "Copy wallpaper files"
      ansible.builtin.copy:
        src: files/*
        dest: /home/{{ ansible_user_id }}/Pictures/*
        owner: root
        group: root
        mode: 0777
      become: true
