- name: Add Slack APT key
  become: true
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present
- name: Add Chrome APT key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
- name: Add Slack repository
  apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    state: present
    filename: slack
- name: Add Chrome repository
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
- name: Install packages
  apt:
    update_cache: yes
    name:
    - htop
    - mc
    - git
    - curl
    - zsh
    - whois
    - uuid
    - jq
    - tlp
    - flameshot
    - filezilla
    - dconf-cli
    - remmina
    - google-chrome-stable
    - slack-desktop
    - python3-pip
    #- python-psutil
    state: present
