- name: Add Criteo APT key
  apt_key:
    url: https://repo.criteois.com/criteo.asc
    state: present
- name: Add Slack APT key
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present
- name: Add Chrome APT key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
- name: Add Criteo repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.criteois.com/ubuntu/ focal main
    state: present
    filename: criteo
    update_cache: yes
- name: Add Slack repository
  apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    state: present
    filename: slack
    update_cache: yes
- name: Add Chrome repository
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
    update_cache: yes
- name: Install packages
  apt:
    name:
    - htop
    - mc
    - git
    - curl
    - zsh
    - whois
    - uuid
    - jq
    - flameshot
    - filezilla
    - google-chrome-stable
    - slack-desktop
    - criteo-setup
    - criteo-anyconnect
    state: present