- name: Install packages
  apt:
    update_cache: yes
    name:
    - htop
    - mc
    - git
    - curl
    - zsh
    - whois
    - uuid
    - jq
    - tlp
    - flameshot
    - filezilla
    - dconf-cli
    - remmina
    - python3-pip
    - python3-psutil
    - kazam
    - cifs-utils
    - fonts-firacode
    state: present
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
- name: Install Brave Browser
  flatpak:
    name: com.brave.Browser
    state: present
    method: user
